version: '2'
services:
  transmission:
    build:
     context: ./
     dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OPENVPN_PROVIDER=EXPRESSVPN
      - OPENVPN_USERNAME=***REMOVED***
      - OPENVPN_PASSWORD=***REMOVED***
      - OPENVPN_CONFIG=my_expressvpn_usa_-_miami_udp
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/16
